# Generated by Django 2.2 on 2019-04-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutreProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Autre produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CourseAutre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.PositiveIntegerField()),
                ('autre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.AutreProduit')),
            ],
        ),
        migrations.CreateModel(
            name='CourseIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('tempsPreparation', models.IntegerField(verbose_name='Temps de préparation (en min)')),
                ('contenu', models.TextField()),
                ('dateDernierePrepa', models.DateField(verbose_name='Date de dernière préparation')),
            ],
            options={
                'verbose_name': 'Recette',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='RecetteIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.Ingredient')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.Recette')),
            ],
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients',
            field=models.ManyToManyField(through='cuisine.RecetteIngredient', to='cuisine.Ingredient'),
        ),
        migrations.CreateModel(
            name='ListeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('commentaire', models.TextField(null=True)),
                ('autre', models.ManyToManyField(through='cuisine.CourseAutre', to='cuisine.AutreProduit')),
                ('ingredients', models.ManyToManyField(through='cuisine.CourseIngredient', to='cuisine.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Frigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.PositiveIntegerField(default=0)),
                ('dlc', models.DateField(null=True, verbose_name='Date limite de consomation')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.Ingredient')),
            ],
            options={
                'verbose_name': 'Frigo',
                'ordering': ['ingredient'],
            },
        ),
        migrations.AddField(
            model_name='courseingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.Ingredient'),
        ),
        migrations.AddField(
            model_name='courseingredient',
            name='listeCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.ListeCourse'),
        ),
        migrations.AddField(
            model_name='courseautre',
            name='listeCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuisine.ListeCourse'),
        ),
    ]
