# Generated by Django 2.2 on 2019-04-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listecourse',
            name='commentaire',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
