# Generated by Django 2.2 on 2019-04-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0003_auto_20190423_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetteingredient',
            name='nombre',
        ),
        migrations.AddField(
            model_name='recetteingredient',
            name='quantite',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autreproduit',
            name='nom',
            field=models.CharField(max_length=60, verbose_name='Nom'),
        ),
    ]
