# Generated by Django 2.2 on 2019-04-26 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0004_auto_20190425_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='calorie',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calorique'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='difficulte',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Difficulté'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='tempsPreparation',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Temps de préparation (en min)'),
        ),
        migrations.AlterField(
            model_name='recetteingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recetteingredient',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.Recette'),
        ),
    ]
