# Generated by Django 2.2 on 2019-04-26 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0005_auto_20190426_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='difficulte',
            field=models.PositiveIntegerField(choices=[(1, 'Très Facile'), (2, 'Facile'), (3, 'Moyen'), (4, 'Difficile'), (5, 'Très Difficile')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Difficulté'),
        ),
    ]
