# Generated by Django 2.2 on 2019-04-26 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0006_auto_20190426_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='calorie',
            field=models.PositiveIntegerField(choices=[(1, 'Très peu calorique'), (2, 'Peu calorique'), (3, 'Normal'), (4, 'Calorique'), (5, 'Très Calorique')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calorique'),
        ),
    ]
