# Generated by Django 2.2 on 2019-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0007_auto_20190426_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autreproduit',
            name='nom',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='nom',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
