# Generated by Django 2.2 on 2019-05-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0008_auto_20190429_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frigo',
            name='dlc',
        ),
        migrations.AlterField(
            model_name='frigo',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recetteingredient',
            name='quantite',
            field=models.FloatField(max_length=5),
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5, unique=True)),
                ('quantite', models.FloatField(max_length=5)),
                ('unite_mere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.Unite')),
            ],
            options={
                'verbose_name': 'Unité',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='recetteingredient',
            name='unite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuisine.Unite'),
        ),
    ]
