# Generated by Django 2.2 on 2019-05-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0009_auto_20190502_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='diminutif',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unite',
            name='nom',
            field=models.CharField(max_length=25),
        ),
    ]
