# Generated by Django 2.2 on 2019-05-02 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0013_recette_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frigo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='frigo',
            name='quantite',
            field=models.FloatField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frigo',
            name='unite',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cuisine.Unite'),
            preserve_default=False,
        ),
    ]
