# Generated by Django 2.2 on 2019-05-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0014_auto_20190502_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autreproduit',
            options={'ordering': ['nom'], 'permissions': (('utiliser_produit', 'Voir, Ajouter un produit'), ('modifier_produit', 'Modifier, Supprimer un produit')), 'verbose_name': 'Autre produits'},
        ),
        migrations.AlterModelOptions(
            name='frigo',
            options={'ordering': ['ingredient'], 'permissions': (('gerer_frigo', 'Modifier le frigo'),), 'verbose_name': 'Frigo'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['nom'], 'permissions': (('utiliser_ingredient', 'Voir, Ajouter un ingrédient'), ('modifier_ingredient', 'Modifier, Supprimer un ingrédient')), 'verbose_name': 'Ingredient'},
        ),
        migrations.AlterModelOptions(
            name='listecourse',
            options={'permissions': (('utiliser_liste_course', 'Ajouter, Voir, Modifier une liste de course'), ('effacer_liste_course', 'Supprimer une liste de course'))},
        ),
        migrations.AlterModelOptions(
            name='recette',
            options={'ordering': ['titre'], 'permissions': (('utiliser_recette', 'Ajouter, Voir une recette'), ('modifier_recette', 'Modifier, Supprimer une recette')), 'verbose_name': 'Recette'},
        ),
        migrations.AlterModelOptions(
            name='unite',
            options={'ordering': ['nom'], 'permissions': (('gerer_unite', 'Gérer les unités'),), 'verbose_name': 'Unité'},
        ),
    ]
