# Generated by Django 2.2 on 2019-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0015_auto_20190502_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseautre',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
