# Generated by Django 2.2 on 2019-05-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0016_auto_20190503_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseingredient',
            old_name='nombre',
            new_name='quantite',
        ),
        migrations.AddField(
            model_name='courseingredient',
            name='unite',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='cuisine.Unite'),
        ),
        migrations.AlterField(
            model_name='recetteingredient',
            name='unite',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='cuisine.Unite'),
        ),
    ]
