# Generated by Django 2.2 on 2019-05-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0017_auto_20190503_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseingredient',
            name='quantite',
            field=models.FloatField(),
        ),
    ]
