# Generated by Django 2.2 on 2019-05-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0019_auto_20190503_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recette',
            options={'ordering': ['categorie', 'titre'], 'permissions': (('utiliser_recette', 'Ajouter, Voir une recette'), ('modifier_recette', 'Modifier, Supprimer une recette')), 'verbose_name': 'Recette'},
        ),
    ]
