# Generated by Django 2.2 on 2019-05-15 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0020_auto_20190503_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('moment', models.PositiveIntegerField(choices=[(1, 'Midi'), (2, 'Soir')], default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Moment de la journée')),
                ('categorie', models.PositiveIntegerField(choices=[(1, 'Entrée'), (2, 'Plat'), (3, 'Dessert')], default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Repas')),
                ('champ_libre', models.CharField(max_length=300, null=True)),
                ('recette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuisine.Recette')),
            ],
        ),
    ]
